const providersData = [
  {
    id: 1,
    razonSocial: "Proveedor ABC S.A.S.",
    nit: "123456789-1",
    tipoEntidad: "juridica",
    tipoProveedor: "Distribuidor",
    contactoPrincipal: "Juan Pérez",
    correo: "contacto@proveedorabc.com",
    telefono: "+57 3001234567",
    direccion: "Calle 10 # 25-30",
    ciudad: "Bogotá",
    descripcion: "Proveedor mayorista de repuestos automotrices.",
    estado: "Activo",
  },
  {
    id: 2,
    razonSocial: "Comercializadora XYZ Ltda.",
    nit: "987654321-2",
    tipoEntidad: "juridica",
    tipoProveedor: "Fabricante",
    contactoPrincipal: "María López",
    correo: "info@xyz.com",
    telefono: "+57 3109876543",
    direccion: "Carrera 15 # 45-60",
    ciudad: "Medellín",
    descripcion: "Fabricante de autopartes nacionales.",
    estado: "Inactivo",
  },
  {
    id: 3,
    razonSocial: "Proveedor con Nombre Largo",
    nit: "123456789-1",
    tipoEntidad: "natural",
    tipoProveedor: "Distribuidor",
    contactoPrincipal: "Ana Gómez",
    correo: "contacto@proveedorlargo.com",
    telefono: "+57 3001234567",
    direccion: "Av. Siempre Viva # 742",
    ciudad: "Cali",
    descripcion: "Proveedor independiente especializado en repuestos.",
    estado: "Activo",
  },
  {
    id: 4,
    razonSocial: "Soluciones Tech S.A.",
    nit: "456789123-4",
    tipoEntidad: "juridica",
    tipoProveedor: "Servicios",
    contactoPrincipal: "Carlos Ruiz",
    correo: "soporte@tech.com",
    telefono: "+57 3209876543",
    direccion: "Calle 50 # 20-15",
    ciudad: "Barranquilla",
    descripcion: "Proveedor de soluciones tecnológicas y software.",
    estado: "Activo",
  },
  {
    id: 5,
    razonSocial: "Importadora Global",
    nit: "789123456-7",
    tipoEntidad: "juridica",
    tipoProveedor: "Importador",
    contactoPrincipal: "Laura Martínez",
    correo: "ventas@global.com",
    telefono: "+57 3012345678",
    direccion: "Cra. 30 # 18-55",
    ciudad: "Cartagena",
    descripcion: "Importador de autopartes internacionales.",
    estado: "Inactivo",
  },
  {
    id: 6,
    razonSocial: "Distribuidora Norte",
    nit: "321654987-0",
    tipoEntidad: "natural",
    tipoProveedor: "Distribuidor",
    contactoPrincipal: "Pedro Sánchez",
    correo: "info@norte.com",
    telefono: "+57 3108765432",
    direccion: "Calle Norte # 12-34",
    ciudad: "Bucaramanga",
    descripcion: "Distribuidor local de repuestos y accesorios.",
    estado: "Activo",
  },
];

export default providersData;
