const employeesData = [
  {
    id: 1,
    nombre: "Paula Andrea",
    apellido: "Vanegas",
    correo: "paula.vanegas@astrostar.com",
    telefono: "3001234567",
    fechaNacimiento: "1985-03-15",
    edad: "39",
    identificacion: "1246789334",
    tipoDocumento: "Cédula de Ciudadanía",
    tipoEmpleado: "Psicólogo",
    rol: "Profesional en Salud",
    estado: "Activo",
    fechaAsignacion: "2023-01-15",
  },
  {
    id: 2,
    nombre: "Estrella",
    apellido: "Betancúr",
    correo: "estrella.betancur@astrostar.com",
    telefono: "3009876543",
    fechaNacimiento: "1990-07-22",
    edad: "34",
    identificacion: "7864108557",
    tipoDocumento: "Cédula de Ciudadanía",
    tipoEmpleado: "Administrativo",
    rol: "Profesional Deportivo",
    estado: "Incapacitado",
    fechaAsignacion: "2023-02-10",
  },
  // {
  //   nombre: "Valentina Zapata",
  //   identificacion: "CC.1397543865",
  //   tipoEmpleado: "Fisioterapeuta",
  //   rol: "Profesional en salud",
  //   estado: "Vacaciones",
  // },
  // {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
  //   {
  //   nombre: "Héctor Vanegas",
  //   identificacion: "CC.1098653986",
  //   tipoEmpleado: "Entrenador",
  //   rol: "Profesional deportivo",
  //   estado: "Retirado",
  // },
];

export default employeesData;
