export const sampleEvents = [
  {
    id: "1",
    tipo: "Torneo",
    nombre: "Torneo Sub 17",
    descripcion: "Torneo nacional de fútbol con categoría sub - 17",
    fechaInicio: "2025-10-22",
    fechaFin: "2025-10-24",
    ubicacion: "Centro Acuático Olímpico",
    telefono: "555-123-4567",
    imagen: "natacion.jpg",
    cronograma: "Día 1: Eliminatorias, Día 2: Semifinales, Día 3: Finales",
    patrocinador: ["Natipan", "Gatorade"],
    categoria: "Deportivo",
    estado: "Activo",
    publicar: true,
  },
  {
    id: "2",
    tipo: "Festival",
    nombre: "Festival 2025 FMV",
    descripcion: "Festival 2025 FMV",
    fechaInicio: "2025-10-15",
    fechaFin: "2025-10-15",
    ubicacion: "Auditorio Central",
    telefono: "555-987-6543",
    imagen: "nutricion.jpg",
    cronograma: "9:00 - Registro, 10:00 - Festival",
    patrocinador: ["NutriSport", "Herbalife"],
    categoria: "Educativo",
    estado: "Activo",
    publicar: true,
  },
  {
    id: "3",
    tipo: "Clausura",
    nombre: "Clausura 2025",
    descripcion:
      "Presentación de los mejores gimnastas del país en una exhibición de alto nivel.",
    fechaInicio: "2025-10-30",
    fechaFin: "2025-10-30",
    ubicacion: "Coliseo Municipal",
    telefono: "555-456-7890",
    imagen: "gimnasia.jpg",
    cronograma: "Clausura, 20:30",
    patrocinador: ["Nike", "Red Bull"],
    categoria: "Deportivo",
    estado: "Programado",
    publicar: true,
  },
  {
    id: "4",
    tipo: "Festival",
    nombre: "Festival Deportivo",
    descripcion:
      "Aprende técnicas avanzadas de entrenamiento funcional para mejorar tu rendimiento deportivo.",
    fechaInicio: "2025-10-28",
    fechaFin: "2025-10-29",
    ubicacion: "Centro Deportivo Elite",
    telefono: "555-789-0123",
    imagen: "funcional.jpg",
    cronograma: "Día 1: Fundamentos, Día 2: Técnicas avanzadas",
    patrocinador: ["Adidas", "Under Armour"],
    categoria: "Educativo",
    estado: "Programado",
    publicar: true,
  },
  {
    id: "5",
    tipo: "Taller",
    nombre: "Taller Homecenter",
    descripcion:
      "Aprende técnicas avanzadas de entrenamiento funcional para mejorar tu rendimiento deportivo.",
    fechaInicio: "2025-10-25",
    fechaFin: "2025-10-26",
    ubicacion: "Centro Deportivo Elite",
    telefono: "555-789-0123",
    imagen: "funcional.jpg",
    cronograma: "Día 1: Fundamentos, Día 2: Técnicas avanzadas",
    patrocinador: ["Homecenter"],
    categoria: "Educativo",
    estado: "Programado",
    publicar: true,
  },
];
