// src/features/dashboard/pages/Admin/pages/Athletes/AthletesData.js

const athletesData = [
  {
    id: 1,
    nombres: "Carlos Andrés",
    apellidos: "Rodríguez Martínez",
    tipoDocumento: "cedula",
    numeroDocumento: "1234567890",
    fechaNacimiento: "1995-03-15",
    genero: "masculino",
    telefono: "+57 3001234567",
    correo: "carlos.rodriguez@email.com",
    direccion: "Calle 45 #12-34, Barrio Los Pinos",
    ciudad: "Bogotá",
    deportePrincipal: "futbol",
    categoria: "profesional",
    posicion: "Delantero",
    equipoClub: "Millonarios FC",
    peso: 75.5,
    estatura: 1.78,
    contactoEmergencia: "María Rodríguez - 3009876543",
    observaciones: "Jugador destacado con experiencia internacional. Lesión en rodilla derecha en 2023, completamente recuperado.",
    estado: "Activo"
  },
  {
    id: 2,
    nombres: "Ana María",
    apellidos: "González Herrera",
    tipoDocumento: "cedula",
    numeroDocumento: "1087654321",
    fechaNacimiento: "1998-07-22",
    genero: "femenino",
    telefono: "+57 3109876543",
    correo: "ana.gonzalez@email.com",
    direccion: "Carrera 15 #67-89, Conjunto Residencial El Dorado",
    ciudad: "Medellín",
    deportePrincipal: "natacion",
    categoria: "elite",
    posicion: "Estilo Libre",
    equipoClub: "Club Nauticus",
    peso: 62.0,
    estatura: 1.65,
    contactoEmergencia: "Pedro González - 3187654321",
    observaciones: "Medallista nacional en estilo libre 100m y 200m. Clasificada para competencias internacionales 2024.",
    estado: "Activo"
  },
  {
    id: 3,
    nombres: "Miguel",
    apellidos: "Torres Silva",
    tipoDocumento: "cedula",
    numeroDocumento: "1098765432",
    fechaNacimiento: "2000-11-08",
    genero: "masculino",
    telefono: "+57 3156789012",
    correo: "miguel.torres@email.com",
    direccion: "Avenida 80 #23-45, Apartamento 501",
    ciudad: "Cali",
    deportePrincipal: "atletismo",
    categoria: "juvenil",
    posicion: "Velocista 100m",
    equipoClub: "Club Atlético Cali",
    peso: 68.3,
    estatura: 1.73,
    contactoEmergencia: "Carmen Torres - 3002468135",
    observaciones: "Promesa del atletismo nacional. Récord departamental en 100 metros planos categoría juvenil.",
    estado: "Activo"
  },
  {
    id: 4,
    nombres: "Isabella",
    apellidos: "Moreno Castro",
    tipoDocumento: "cedula",
    numeroDocumento: "1076543210",
    fechaNacimiento: "1996-05-30",
    genero: "femenino",
    telefono: "+57 3187654321",
    correo: "isabella.moreno@email.com",
    direccion: "Calle 100 #15-20, Zona Norte",
    ciudad: "Barranquilla",
    deportePrincipal: "voleibol",
    categoria: "profesional",
    posicion: "Atacante",
    equipoClub: "Voleibol Barranquilla",
    peso: 68.7,
    estatura: 1.82,
    contactoEmergencia: "Luis Moreno - 3009876543",
    observaciones: "Capitana del equipo nacional juvenil. Participación en Sudamericano 2023 con excelentes resultados.",
    estado: "Inactivo"
  },
  {
    id: 5,
    nombres: "Andrés Felipe",
    apellidos: "Vargas López",
    tipoDocumento: "cedula",
    numeroDocumento: "1054321098",
    fechaNacimiento: "1993-12-10",
    genero: "masculino",
    telefono: "+57 3129876543",
    correo: "andres.vargas@email.com",
    direccion: "Carrera 7 #45-67, Centro Histórico",
    ciudad: "Bogotá",
    deportePrincipal: "tenis",
    categoria: "profesional",
    posicion: "Individual",
    equipoClub: "Club El Nogal",
    peso: 73.2,
    estatura: 1.80,
    contactoEmergencia: "Sandra López - 3156789012",
    observaciones: "Rankeado en top 500 ATP. Múltiples títulos nacionales y participación en torneos internacionales.",
    estado: "Activo"
  },
  {
    id: 6,
    nombres: "Sofía",
    apellidos: "Ramírez Pineda",
    tipoDocumento: "cedula",
    numeroDocumento: "1043210987",
    fechaNacimiento: "2001-02-18",
    genero: "femenino",
    telefono: "+57 3098765432",
    correo: "sofia.ramirez@email.com",
    direccion: "Calle 85 #12-30, Barrio La Castellana",
    ciudad: "Medellín",
    deportePrincipal: "gimnasia",
    categoria: "juvenil",
    posicion: "Artística",
    equipoClub: "Gimnasio Integral",
    peso: 52.5,
    estatura: 1.58,
    contactoEmergencia: "Patricia Pineda - 3187654321",
    observaciones: "Medallista de oro en campeonato nacional juvenil. Preparación para competencias internacionales.",
    estado: "Activo"
  },
  {
    id: 7,
    nombres: "Juan David",
    apellidos: "Hernández Restrepo",
    tipoDocumento: "cedula",
    numeroDocumento: "1032109876",
    fechaNacimiento: "1997-09-25",
    genero: "masculino",
    telefono: "+57 3165432109",
    correo: "juan.hernandez@email.com",
    direccion: "Avenida Las Palmas #67-89, El Poblado",
    ciudad: "Medellín",
    deportePrincipal: "ciclismo",
    categoria: "profesional",
    posicion: "Ruta",
    equipoClub: "Team Colombia Cycling",
    peso: 65.8,
    estatura: 1.75,
    contactoEmergencia: "Gloria Restrepo - 3129876543",
    observaciones: "Especialista en alta montaña. Participación en Tour Colombia y competencias internacionales.",
    estado: "Activo"
  },
  {
    id: 8,
    nombres: "Valentina",
    apellidos: "Ospina Cortés",
    tipoDocumento: "cedula",
    numeroDocumento: "1021098765",
    fechaNacimiento: "1999-04-12",
    genero: "femenino",
    telefono: "+57 3054321098",
    correo: "valentina.ospina@email.com",
    direccion: "Calle 95 #20-15, Zona Rosa",
    ciudad: "Bogotá",
    deportePrincipal: "taekwondo",
    categoria: "elite",
    posicion: "Peso Mosca",
    equipoClub: "Academia Taekwondo Elite",
    peso: 49.2,
    estatura: 1.63,
    contactoEmergencia: "Ricardo Ospina - 3098765432",
    observaciones: "Cinturón negro 3er Dan. Medallista panamericana y clasificada para competencias mundiales.",
    estado: "Activo"
  }
];

export default athletesData;